import { IFAQ } from "@/types";

export const faqs: IFAQ[] = [
  {
    question: `How does TweetGenius work?`,
    answer: 'Just enter a topic or prompt, and TweetGenius will instantly generate high-quality tweets tailored to your input.',
  },
  {
    question: `Is TweetGenius free to use?`,
    answer: 'Yes! You can generate tweets for free and as often as you like.',
  },
  {
    question: 'What kind of tweets can it generate?',
    answer: 'TweetGenius can create informative, witty, promotional, or opinion-based tweets—just describe what you’re looking for.',
  },
  {
    question: 'Can I use it for my business or personal brand?',
    answer: 'Absolutely! Whether you’re a founder, freelancer, or content creator, TweetGenius helps you stay active and consistent.',
  },
  {
    question: 'Are the tweets original?',
    answer: 'Yes. Each tweet is uniquely generated by AI and not pulled from existing posts.',
  },
  {
    question: 'Do I need an account to use TweetGenius?',
    answer: 'No account is required. Just visit the site and start generating tweets—no sign-up needed.',
  },
  {
    question: 'Can I generate more than one tweet at a time?',
    answer: 'Yes. You can choose how many tweets to generate in one go—perfect for batching your content.',
  },
  {
    question: 'Is my input or generated content stored?',
    answer: 'No. We don’t save or share your prompts or tweets. Everything stays private.',
  },
  {
    question: 'Can I edit the tweets after generation?',
    answer: 'Yes! We recommend reviewing and customizing the tweets before publishing to match your voice.',
  },
  {
    question: 'What if the tweets don’t fit my brand tone?',
    answer: 'Try refining your prompt or providing a bit more context—TweetGenius adapts based on your input.',
  },
  {
    question: 'Is TweetGenius suitable for non-tech users?',
    answer: 'Yes. It’s super simple—no technical skills needed. Just type and go.',
  },
  {
    question: 'Can I use it to go viral?',
    answer: 'While we can’t promise virality, TweetGenius is designed to help you post more consistently and creatively—which gives you a much better shot!',
  },
];
